name: Build Windows EXE (Win7+ compatible)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller==5.13.0

      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          pyinstaller --noconfirm --clean ^
            --onefile ^
            --windowed ^
            --icon=excel_pdf_matcher_icon.ico ^
            excel_pdf_gui.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel_pdf_gui.exe
          path: dist/excel_pdf_gui.exe
